[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc-version = "0.8.14"

[profile.stg]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc-version = "0.8.14"

[profile.prd]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./"}]
solc-version = "0.8.14"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config